// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC956p7--et2ItWVcxeNZMGQXvWIw-1YOk',
    appId: '1:601042311403:web:8f46c2ea67614153c286ae',
    messagingSenderId: '601042311403',
    projectId: 'fintrack-4df01',
    authDomain: 'fintrack-4df01.firebaseapp.com',
    storageBucket: 'fintrack-4df01.firebasestorage.app',
    measurementId: 'G-FXL162NV9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXg9jS9NGhJ8dPdKMU1we09lgZTRfJsvM',
    appId: '1:601042311403:android:59ed53e20d210bf2c286ae',
    messagingSenderId: '601042311403',
    projectId: 'fintrack-4df01',
    storageBucket: 'fintrack-4df01.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATAoGrLKOW1WZWuBols3xWzId_bQZpgQQ',
    appId: '1:601042311403:ios:3c97cc08dd081b66c286ae',
    messagingSenderId: '601042311403',
    projectId: 'fintrack-4df01',
    storageBucket: 'fintrack-4df01.firebasestorage.app',
    iosClientId: '601042311403-6kh9i19i05hnh8kk9kpe2v4qpmtpmprp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
